language: go
sudo: false
go:
  - 1.6.2
  - tip
install:
  - go get -t ./...
  - go get github.com/golang/lint/golint
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - go vet ./...
  - test -z "$(golint ./... | tee /dev/stderr)"
  - test -z "$(gofmt -s -l . | tee /dev/stderr)"
  - go test -race -v -coverprofile=trylock.coverprofile ./...
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci